### ISSUE TITLE
FYI: v1.1.0 did not release

### ISSUE THREAD

**Issue by di** [PyCQA/doc8#124]
The workflow failed to run: https://github.com/PyCQA/doc8/actions/runs/3748087258

**Comment by ssbarnea** [comment]
@di Feel free to send the regards for this breakage to @webknjaz as that is his doing - removal of `v1` tag, that also being the only github action creator that decided to go for not using the mobile tags, even removing existing ones.

**Comment by webknjaz** [comment]
That tag never existed in the first place 🤷‍♂️

**Comment by ssbarnea** [comment]
That is weird because it means that the pipeline never worked... I hope if fixed it for now. I have zero desire to make PRs to update release pipeline on each minor fix made to it.

**Comment by miketheman** [comment]
1.1.1 is now live on PyPI, thanks!
1.1.0 never made it, due to the pipeline breakage. https://pypi.org/project/doc8/#history Might be useful to note that in the [release notes](https://github.com/PyCQA/doc8/releases/tag/v1.1.0) for whomever comes looking.

**Comment by di** [comment]
I see a 1.1.1 on PyPI now. I'll leave this open to decide whether 1.1.0 should also get a manual release. They appear to be the same.

**Comment by ssbarnea** [comment]
They are the same, I only repaired the pipeline. I will remove the 1.1.0 release from the page as it never effectively went "all the way out".

**Comment by ssbarnea** [comment]
PS. THanks for creating the bug, I forgot to check that it was publishied.
