### ISSUE TITLE
[REQUEST] Adding setup.py for doc8

### ISSUE THREAD

**Issue by D3vil0p3r** [PyCQA/doc8#129]
Hello,
for the Arch Linux environment, I would like to create a PKGBUILD for making a package instead of installing doc8 by pip. Among the source files I could not see a `setup.py` that could be great to have for making easily the creation of a PKGBUILD.

Could you please submit a `setup.py` file in order to install the module instead of using pip?

**Comment by ssbarnea** [comment]
This will not happen, please read [PEP-621](https://peps.python.org/pep-0621/) for details.

Over the last few months I removed `setup.cfg` and `setup.py` from numerous python libraries, including several which were identified as critical by pypa itself.

**Comment by D3vil0p3r** [comment]
> This will not happen, please read [PEP-621](https://peps.python.org/pep-0621/) for details.
> 
> Over the last few months I removed `setup.cfg` and `setup.py` from numerous python libraries, including several which were identified as critical by pypa itself.

Did you delete it from those python libraries because setuptools is deprecated and will be removed on Python 3.12?

**Comment by ssbarnea** [comment]
Read again, setuptools was never part of stdlib and is not going anywhere. The bit removed in 3.12 is distutils, something quite different.

Some of the library I was involved with adoption of PEP-621 can be seen at https://github.com/topics/pep-621
