### ISSUE TITLE
doc8 git pre-commit hook fails but command line tool works

### ISSUE THREAD

**Issue by zaneselvans** [PyCQA/doc8#14]
I just added `doc8` to my pre-commit configuration (using the most recent hash a4740d8f4f41ce4e1e1d1b7dedc8f928f365b862 as the version), and when committing a change to my `README.rst` I got the following failure:

```
doc8.....................................................................Failed
hookid: doc8

Traceback (most recent call last):
  File "/home/zane/miniconda3/envs/pudl/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zane/miniconda3/envs/pudl/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zane/.cache/pre-commit/repomemqz1cs/py_env-python3.7/lib/python3.7/site-packages/doc8/__main__.py", line 20, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable
```

I ran `pre-commit clean` and then attempted the commit again, and got the same error.  However, when I run `doc8` against the same file on the command line, it succeeds. Maybe there's something wonky with the script entrypoint arrangement?

From my `.pre-commit-config.yml` file:
```yml
# Check for errors in reST files under the doc hierarchy
- repo: https://github.com/PyCQA/doc8
  rev: a4740d8f4f41ce4e1e1d1b7dedc8f928f365b862
  hooks:
  - id: doc8
```

I thought the problem might be a mismatch between the installed v0.8.0 of `doc8` and the most recent commit to master, so did `pip install git+https://github.com/PyCQA/doc8.git` in my conda environment, which gave me v0.8.1.dev19, but I got the exact same behavior. `doc8 --version` now gives 0.8.1 and when I do `conda list | grep doc8` I get `0.8.1.dev19` so I think it really is using the version from the repository.

**Comment by stephenfin** [comment]
Whoops. My mistake. This has been resolved now.

**Comment by zaneselvans** [comment]
Thanks! Working fine for me on the new version.
