### ISSUE TITLE
More than two years since last release on PyPI

### ISSUE THREAD

**Issue by jvillal-amp** [PyCQA/doc8#23]
It has been more than two years since the last release of this project on PyPI: https://pypi.org/project/doc8/#history

Any plans to push a new release?

**Comment by radiac** [comment]
A release would be great, I'm waiting to use merged #17 in production code.

**Comment by ssbarnea** [comment]
@harlowja Can you help with https://pypi.org/project/doc8/ permissions so we can make a release?

**Comment by harlowja** [comment]
Sure, will do.

**Comment by harlowja** [comment]
Done.

**Comment by adamtheturtle** [comment]
@ssbarnea I'm also waiting on a release and happy to contribute in some way if that would help.

**Comment by stephenfin** [comment]
I have pushed 0.8.1.
