### ISSUE TITLE
doc8 reports unnecessary D002 and D004 on Windows line ending

### ISSUE THREAD

**Issue by dpizetta** [PyCQA/doc8#33]
Hi, still having this problem.

It should be nice import all issues reported here: https://bugs.launchpad.net/doc8/+bug/1756704

Check the versions in [pip_list.txt](https://github.com/PyCQA/doc8/files/4369684/pip_list.txt)

**Comment by ssbarnea** [comment]
Will all due respect to Windows users, AFAIK even its notepad started to work fine with standard newlines.

I have no interest in supporting such "deviations" but if another maintainer thinks it needs fixing, I will not fight against it.

**Comment by MarkusPiotrowski** [comment]
I guess the main problem that it reports D004 **and** D002. While I would happily turn off D004, I wouldn't do this with D002.

**Comment by peterjc** [comment]
Python itself has been pragmatic about the different operating system standards for new lines. Python 2 had optional universal newline support, while Python 3 does this by default in text mode. I see no reason for doc8 not to cope with Windows new lines too.

Would you (or another maintainer) review a pull request fixing this? I think it could be as simple as handling Windows ``\r\n`` as well as Linux/macOS style ``\n`` here:

https://github.com/PyCQA/doc8/blob/db40a1a30521b00e0c47b5095d9dcef39412919d/doc8/parser.py#L92

(Plus a test case)

**Comment by ssbarnea** [comment]
I would not support this change but I would not block it. I think means that @stephenfin is your only chance to getting it accepted.

**Comment by stephenfin** [comment]
Yup, happy to review a PR 👌 I don't have a Windows environment to test in though

**Comment by peterjc** [comment]
Thank you @MarkusPiotrowski and @ssbarnea 👍
