### ISSUE TITLE
When will the next release be?

### ISSUE THREAD

**Issue by takos22** [PyCQA/doc8#55]
So I have an error ``Error in "code-block" directive: unknown option: "linenos".`` but it has been reported in #30 and resolved in #51, but it hasn't been released yet so I would need to install the github repo. It would be easier to release a new version on PyPI because 0.8.1 doesn't have the fix implemented.

**Comment by kasium** [comment]
+1 for this question. I looking forward for the pyproject.toml support

**Comment by ssbarnea** [comment]
I just released 0.9.0 via https://github.com/PyCQA/doc8/discussions/62
