### ISSUE TITLE
doc8 does not load ignore-path from pyproject.toml

### ISSUE THREAD

**Issue by ssbarnea** [PyCQA/doc8#75]
I tried used two versions of what it was supposed to be config in toml file and I observed that running `doc8` failed to use the ignore. On the other hand putting configuration inside `setup.cfg` worked.

# case 1
```
# pyproject.toml
[tool.doc8]
ignore-path = [".tox"]
```

# case 2
```
# pyproject.toml
[tool.doc8]
ignore-path = ".tox"
```

None of these works and based on docs, at least should have worked.

**Comment by ssbarnea** [comment]
A patch would be welcomed.

**Comment by ejd** [comment]
See #85

**Comment by ejd** [comment]
This issue is now resolved.
