### ISSUE TITLE
Setup config failing with `0.10.1`

### ISSUE THREAD

**Issue by fmigneault** [PyCQA/doc8#77]
Starting with version `0.10.1`, the `ignore-path` and `max-line-length` defined in `setup.cfg` fails to be considered. 

My configuration is as follows:
```cfg
[doc8]
max-line-length = 120
ignore-path = docs/_build,docs/autoapi
```

I call the following command:
```shell
doc8 --config "./setup.cfg" "./docs"
```

With version `0.10.0`, my project outputs:
```
Scanning...
Validating...
========
Total files scanned = 11
Total files ignored = 18
Total accumulated errors = 0
Detailed error counts:
    - doc8.checks.CheckCarriageReturn = 0
    - doc8.checks.CheckIndentationNoTab = 0
    - doc8.checks.CheckMaxLineLength = 0
    - doc8.checks.CheckNewlineEndOfFile = 0
    - doc8.checks.CheckTrailingWhitespace = 0
    - doc8.checks.CheckValidity = 0
```

With version `0.10.1`, many errors are reported. 
All errors correspond to either a dir supposed to be ignored or a line that is correct in length according to my config (not the default) :

<details>
<summary>Expand for details</summary>
<pre><code>
Scanning...
Validating...
/home/francis/dev/devops/makefile/docs/source/references.rst:2: D001 Line too long
/home/francis/dev/devops/makefile/docs/source/toc.rst:6: D001 Line too long
/home/francis/dev/devops/makefile/docs/source/toc.rst:7: D001 Line too long
/home/francis/dev/devops/makefile/docs/source/installation.rst:13: D001 Line too long
/home/francis/dev/devops/makefile/docs/source/installation.rst:14: D001 Line too long
/home/francis/dev/devops/makefile/docs/source/installation.rst:22: D001 Line too long
/home/francis/dev/devops/makefile/docs/source/installation.rst:24: D001 Line too long
/home/francis/dev/devops/makefile/docs/source/installation.rst:25: D001 Line too long
/home/francis/dev/devops/makefile/docs/source/installation.rst:26: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/README.md.txt:3: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/README.md.txt:3: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/README.md.txt:4: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/README.md.txt:7: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/README.md.txt:8: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/index.rst.txt:11: D005 No newline at end of file
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:18: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:23: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:28: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:33: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:38: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:43: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:46: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:48: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:51: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:53: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:56: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:58: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:63: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:68: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:71: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:73: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:76: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:78: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:83: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:86: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:88: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:93: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:96: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:98: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:101: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:103: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:106: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:108: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:111: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:113: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:116: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:118: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:121: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:123: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:126: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:128: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:131: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/__meta__/index.rst.txt:133: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:22: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:24: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:27: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:29: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:32: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:34: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:37: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:39: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:42: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:44: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:47: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/autoapi/source/cli/index.rst.txt:49: D002 Trailing whitespace
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/toc.rst.txt:6: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/toc.rst.txt:7: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/references.rst.txt:2: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/references_page.rst.txt:9: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/installation.rst.txt:13: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/installation.rst.txt:14: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/installation.rst.txt:22: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/installation.rst.txt:24: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/installation.rst.txt:25: D001 Line too long
/home/francis/dev/devops/makefile/docs/_build/html/_sources/source/installation.rst.txt:26: D001 Line too long
========
Total files scanned = 29
Total files ignored = 0
Total accumulated errors = 75
Detailed error counts:
    - doc8.checks.CheckCarriageReturn = 0
    - doc8.checks.CheckIndentationNoTab = 0
    - doc8.checks.CheckMaxLineLength = 23
    - doc8.checks.CheckNewlineEndOfFile = 1
    - doc8.checks.CheckTrailingWhitespace = 51
    - doc8.checks.CheckValidity = 0
make: *** [Makefile:1068: check-doc8-only] Error 1
</code></pre>
</details>

**Comment by ssbarnea** [comment]
PR welcomed
