### ISSUE TITLE
Activate travis

### ISSUE THREAD

**Issue by ssbarnea** [PyCQA/doc8#9]
Travis is not enabled on `PyCQA/doc8` and I do not have enough permissions to do it myself, please help with this as this is No1 priority before doing any other work.

**Comment by sigmavirus24** [comment]
The app is installed for PyCQA which means you should be able to enable it here but I'll verify that for y'all.

**Comment by sigmavirus24** [comment]
Yep, it does appear as though it should be working going forward. You can close/reopen existing PRs to get it to check-in on those iirc
