### ISSUE TITLE
Inclusion of pip in `pyproject.toml` causing failed builds

### ISSUE THREAD

**Issue by grgmiller** [PyCQA/doc8#91]
Per https://github.com/pypa/pip/issues/11120, including pip in pyproject.toml [build-system] requires causes failures when trying to install doc8. 

I've been experiencing this issue as described https://github.com/catalyst-cooperative/pudl/issues/1742#issuecomment-1178533709, when pre-commit is trying to install the virtual environment that includes doc8. 

I think that if pip were removed from your toml file, it would likely solve this issue.

**Comment by ssbarnea** [comment]
@grgmiller Yep, please make a PR to fix it. In fact it would be good idea to update the packaging pipeline to use "build" module too.

**Comment by ssbarnea** [comment]
Fixed by #94, release very soon.
